### ISSUE TITLE
HTML-ize the docs

### ISSUE THREAD

**Issue by neogeographica** [neogeographica/quakestarter#70]
It's going to be a bit of a task but I think it's past time... they're too sprawling and interconnected to be nicely browsable just as textfiles now.

One initial job here is to pick some kind of authoring method/framework, I probably shouldn't just completely hand-hack the HTML.

**Comment by GenericJohnDoeNO0** [comment]
A thought i am carrying with me for a while for my own pack: A html instead of / or as gui for my selector.bat with fancy pictures (_If provided_) and an option to read the readme. Someday i will go this task on, maybe as an html, maybe as an c# lesson for my self... 

God may safe us both and show our minds mercy... ;)

But until then: What if you would use your scripts to ad the readme as an option per map as an additional choice? So you could reuse some short code and just copy and paste it and then add the filename to read in the cmd or in notepad/editor?

**Comment by neogeographica** [comment]
I think you're talking about the per-map readmes right? This particular issue is more about how to handle Quakestarter's own bucket of readmes (currently in the quakestarter_docs folder).

But yeah providing a way to view more per-map info -- either viewing the map's readme file or opening the Quaddicted page -- would be great. I think I'm mainly just not sure how to cram that additional option into these text menus that are already too busy. Especially the option to view a Quaddicted page, you'd really want to see that before downloading the mod, so it would need to be something doable from the main menus.

**Comment by neogeographica** [comment]
One option for documentation source format would be [rST](https://docutils.sourceforge.io/rst.html) since I am (or was) pretty familiar with using rST input to [Sphinx ](https://www.sphinx-doc.org/en/master/index.html)to generate Python module docs.

~~It might also be nice to look into [Pandoc](https://pandoc.org/) as the doc processor, either with rST input or something else. The [TrenchBroom docs](https://trenchbroom.github.io/manual/latest/) use Pandoc well IMO, with [Markdown ](https://daringfireball.net/projects/markdown/ ) input. (Tho TrenchBroom-quality docs could be overkill here.)~~

**Comment by neogeographica** [comment]
Committed to develop branch for next release.
